#!/bin/bash

# Read token and CA cert
TOKEN="eyJhbGciOiJSUzI1NiIsImtpZCI6IlRFUnBNM2gwQ0hFTV9FVWZ2TDl3VUtzVGdaNmtRLVQxc2NFbVlCU0NJMGsifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzUyNzc3MDYwLCJpYXQiOjE3MjEyNDEwNjAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZmFlMGZiZDAtZjU2Mi00ODVjLWE1ZjAtMDI5MDJjNzg3YjlmIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwibm9kZSI6eyJuYW1lIjoibWluaWt1YmUiLCJ1aWQiOiIxYTljMWE2MC0xY2ZlLTQ3NGUtOWExNy04NGMyNDVmM2I5ZjkifSwicG9kIjp7Im5hbWUiOiJ3ZWItNWY2OWY2ZjhkNi13NHN6YyIsInVpZCI6ImVhNjEwZmI4LTk5NDQtNDA2ZC1hM2EzLTQ0NmJhZDNmYjMwOSJ9LCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoid2ViLXNlcnZpY2UtYWNjb3VudCIsInVpZCI6IjFmMDhiZThhLWU0MWEtNDdkMi05ODIxLTA0NjU0MTI4NjM4ZiJ9LCJ3YXJuYWZ0ZXIiOjE3MjEyNDQ2Njd9LCJuYmYiOjE3MjEyNDEwNjAsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OndlYi1zZXJ2aWNlLWFjY291bnQifQ.EqfJyLtvwNuOfgwzFPKbMNxJkYLCaL21axputVyyO_s-TfDOfqcZGuRLapsLAdRcgNKZ2p6kIg5Pxl436tQFa6Z_wTJfQ3BrJbihxOQlVt1--Ji9AqPUks2uDCj483dZMTdGerXeXM6iXHuQOT-BE44Xk4GSd9h3hFBFDQ2d94xsCR3xIfQMN0trAmCNU0iErN9RX0kQ8bG3WZkuGs_Prb-wSFuWK3VZROmZ6K3O9qAvTFY63V_pkQjmjrwF5_ngzF5VlodHtqGDMpJ_vza0CYXpbQaGalYfC2N6ZP95SImjekyOe2v7KGLIryF5xGmrqwnUyirjNpQHGJZeviFvWg"
CA_CERT="-----BEGIN CERTIFICATE-----\nMIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p\na3ViZUNBMB4XDTI0MDcxMjA2MDkzOVoXDTM0MDcxMTA2MDkzOVowFTETMBEGA1UE\nAxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANus\nOIpeNlzYpjRt1yFPt3AAodt3+WyYyqM7TdhkgFw9TJoZKsm3bSlYM4vHkSE3P02E\nnXUYyLz3BsYvvZ/FQmS507+F3PWhlJOQDGPwTcYVtCH0PzG73eNmLsz0mDMKa5AS\nkutp3RmwbtHlXpspxPS5l0hdKKJc7Onyg3trvjA3FqDwJRBC2wMofvSVeiY9s+/6\nz6IgZ7RLN//LeS8esoweAtOLsFhV70Z3f7pPili4IohavZRO8T5lEWAmYiojlpcm\n2jS4loabkkXCjnlUFr5geSWTydB7FE7MkETQG8MI5lYkXgrZhxwzoRYt8Gae4tre\nIfXvhU2YknRuK4pzbqsCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW\nMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW\nBBR7YewyqWoi/9g5JfOdplm29f+2RjANBgkqhkiG9w0BAQsFAAOCAQEAmJ5xEHCe\n58H/8VUQNMMxUee+mZmhJNhR3Z2hV7SHW2Br8QN+E1zjQk5Kv6KxdoIDe5DwZFjg\nBys7JMrhJURLN4/niOqDxKUH+Mpf2bHm9mK3CRJoRBdvk1gCmM0hHZ82rZKzE69t\n86v33rlw0hvb3jzuo6KFXUOPKURqWjqc/c36DG3Yy/9jkM0vmvRmaAEg/kSEQd/T\nw1OHpmEZCvYaBI+JEYtorCxcsWYg3OevFY5cwoFTFd9B1qEOwaRWg7VuCfOzTkBU\ngYz6YUjsNFt19gHpdQOWS1acdmn4o0qAe3hXb3j8jEIhwbWqYvjt1HGgBTnXKwdv\nDZYRLSHZYLciWA==\n-----END CERTIFICATE-----\n"
API_SERVER="https://192.168.64.2:8443"

KUBECONFIG=$(mktemp)

kubectl config set-cluster my-cluster --server=https://192.168.64.2:8443 --certificate-authority=ca.crt --embed-certs=true --kubeconfig=$KUBECONFIG

kubectl config set-credentials my-user --token=$TOKEN --kubeconfig=$KUBECONFIG


kubectl config set-context my-context --cluster=my-cluster --user=my-user --kubeconfig=$KUBECONFIG

kubectl config use-context my-context --kubeconfig=$KUBECONFIG

#kubectl --kubeconfig=$KUBECONFIG get pods -A

#kubectl --kubeconfig=$KUBECONFIG exec  vulnerable-api-demo -n dev-nginx-pods -- env

echo $KUBECONFIG

kubectl --kubeconfig=$KUBECONFIG get pods -A -o wide

kubectl --kubeconfig=$KUBECONFIG exec -it  vulnerable-api-demo -n dev-nginx-pods -- /bin/bash

